### ISSUE TITLE
Don't pwd?

### ISSUE THREAD

**Issue by MitchellHenr** [shyiko/commacd#11]
Hello,

I was wondering if there's an easy way to configure commacd so as not to print the working directory after a change.  I already show the current directory in my command prompt, so it's redundant (in my case) to show it whenever I make a change.  Great feature, just not what I need.  Is there any way to easily do this, or should I try to figure it out?

Thanks,
H.M.

**Comment by shyiko** [comment]
@MitchellHenr Hi. Sure. `export COMMACD_CD="builtin cd"` in your .bashrc should do it.

**Comment by shyiko** [comment]
([reference](https://github.com/shyiko/commacd/blob/master/commacd.bash#L27))
