### ISSUE TITLE
ZSH port

### ISSUE THREAD

**Issue by roboslone** [shyiko/commacd#4]
commacd looks like it can be really useful, do you have any plans for zsh support?

**Comment by shyiko** [comment]
Hi. 

Unfortunately I'm not ZSH user. I would love to get a PR with commacd.zsh in it ;) but until I make a switch I do not intend to make a port myself.

**Comment by fabiantheblind** [comment]
+1

**Comment by skywind3000** [comment]
https://github.com/shyiko/commacd/pull/16
I created a PR for this, and passed all your tests in shpec.

**Comment by shyiko** [comment]
ZSH support merged in. Thanks, @skywind3000!
